/*
 * problem2.c
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * 
 * Vinod VM <vinod@segfault.in>
 */
#include <stdio.h>
#define MILLION 1000000
 
int main(void)
{
	int sum = 2;
	int next = 0, last = 2, second_last = 1;

	do {
		next = last + second_last;
		if(next % 2 == 0)
			sum += next;

		second_last = last; last = next;
	} while(next < 4 * MILLION);

	printf("Sum = %d\n", sum);

	return (0);
}